### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by yancong001** [mscststs/lol-tft#8]
第一次登录可以使用，2 天后再次登录显示空白。注销、重新安装脚本均失败。（Mac book pro, Chrome）
<img width="1414" alt="image" src="https://github.com/mscststs/lol-tft/assets/29802081/cce9af8c-88b6-4d47-a079-9803a880acc2">

**Comment by mscststs** [comment]
这种情况需要手动清一下cookies， 这个页面的登录态过期时间非常随机，回头想个办法判断一下

**Comment by yancong001** [comment]
手动清理后可以了，但是这次清理之前关闭或者重启游览器都不行。

**Comment by mscststs** [comment]
已 fix，后续可以再观察看看
